version: '3.9'
services:
  st-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    container_name: st-node
    volumes:
       - .:/usr/src/simple-twitch-node
    command: [node, index.js]